name: Social Media Content Tracking
description: Plan and track social media posts using sidebar labels and external links.
title: "📱 POST: <Brief description>"
labels: ["social-media", "priority: Medium", "status: To Do"]
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Action Required
        Please use the **Labels** section in the right-hand sidebar to select:
        1. **Post Type** (Image, Carousel, Reel, or Repost)
        2. **Priority Level**
  
  - type: checkboxes
    id: status-checklist
    attributes:
      label: Production Status
      options:
        - label: Content copy written
        - label: Content created (Visuals/Video)
        - label: Social media caption written

  - type: dropdown
    id: post-type-dropdown
    attributes:
      label: Type of Post
      description: Select the format of the content.
      options:
        - "Pick an option"
        - Image
        - Carousel
        - Reel
        - Repost
    validations:
      required: true

  - type: dropdown
    id: topic-area
    attributes:
      label: Topic Area & Objectives
      description: What is the primary goal of this post?
      options:
        - "Pick an option"
        - "1. Calls to Action (CTAs): Mobilize, donate, or contact reps"
        - "2. Coverage of Events: Real-time or next-day visuals"
        - "3. Amplifying Palestinian Voices: Testimonies and art"
        - "4. Movement Updates & News: Key developments from Gaza"
    validations:
      required: true

  - type: input
    id: proton-drive-link
    attributes:
      label: Proton Drive Link
      description: Link to the folder or specific file.
      placeholder: "https://drive.proton.me/urls/..."

  - type: input
