name: Social Media Content Tracking
description: Plan and track social media posts using sidebar labels and external links.
title: "📱 POST: <Brief description>"
labels: ["social-media", "priority: Medium", "status: To Do"]
body:
  - type: checkboxes
    id: status-checklist
    attributes:
      label: Production Status
      options:
        - label: Content copy written
        - label: Content created (Visuals/Video)
        - label: Social media caption written
        - label: APPROVED
        - label: POSTED

  - type: input
    id: date-created
    attributes:
      label: Date Added/Created
      description: When was this idea or request logged?
      placeholder: "YYYY-MM-DD"

  - type: dropdown
    id: topic-area
    attributes:
      label: Area and Objective
      description: What is the primary goal of this post?
      options:
        - "Pick an option"
        - "1. Calls to Action (CTAs): Mobilize, donate, or contact reps"
        - "2. Coverage of Events: Real-time or next-day visuals"
        - "3. Amplifying Palestinian Voices: Testimonies and art"
        - "4. Movement Updates & News: Key developments from Gaza"
    validations:
      required: true

  - type: dropdown
    id: post-type-dropdown
    attributes:
      label: Type of Post
      description: Select the format of the content.
      options:
        - "Pick an option"
        - Image
        - Carousel
        - Reel
        - Repost
    validations:
      required: true

  - type: textarea
    id: post-copywriting
    attributes:
      label: Post Copywriting
      description: Draft the text/information that will be inside the graphics or video here.
      placeholder: "Enter the text for the actual content here..."

  - type: textarea
    id: social-media-caption
    attributes:
      label: Social Media Caption
      description: Draft the caption here. This MUST include relevant hashtags.
      placeholder: "Write the caption here..."

  - type: textarea
    id: hashtags
    attributes:
      label: Template Hashtags
      description: Standard hashtag blocks to include.
      value: "#SailToGaza #GlobalSumudFlotilla #BreakTheSiege #GlobalMovementToGaza"

  - type: textarea
    id: collaborators
    attributes:
      label: Potential Collaborators
      description: If you want to update or add to this list, let Kyle know.
      value: |
        celebrities4palestine, toritsui_, call2actionnow, airbyart, lisamoorish, 
        higherlove_withmegan, katnippresents, xrebellionuk(climate related only), 
        cocktailsandcapitalism

  - type: input
    id: proton-drive-link
    attributes:
      label: Proton Drive Link
      placeholder: "https://drive.proton.me/urls/..."

  - type: input
    id: canva-link
    attributes:
      label: Canva Design Link
      placeholder: "https://www.canva.com/design/..."

  - type: input
    id: post-date
    attributes:
      label: Date of When to Post
      placeholder: "YYYY-MM-DD"

  - type: input
    id: post-time
    attributes:
      label: Time Posted
      placeholder: "e.g., 18:00 GMT"

  - type: markdown
    attributes:
      value: |
        ---
        **Note:** At the bottom of this screen (or in the right sidebar), you can add labels. 
        *Priority will be dictated by the social media lead.*
        
        If you need any help understanding, ask Kyle.
